//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5G5_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public int SalesPersonID { get; set; }
        public string SalesPersonName { get; set; }
        public string SalesPersonTelephone { get; set; }
        public string SalesPersonFax { get; set; }
        public int TerritoryID { get; set; }
    }
}
